# Generated by Django 4.0.1 on 2022-01-20 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionText', models.CharField(max_length=400)),
                ('score', models.FloatField(default=0.0)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='hangapp.user')),
                ('usersVoted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hangapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decisionText', models.CharField(max_length=400)),
                ('options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hangapp.option')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='creator', serialize=False, to='hangapp.user')),
                ('decisions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hangapp.decision')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hangapp.user')),
            ],
        ),
    ]
