# Generated by Django 4.0.1 on 2022-01-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='DefaultUser', max_length=100),
            preserve_default=False,
        ),
    ]
