# Generated by Django 4.0.1 on 2022-01-20 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hangapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decision',
            name='options',
        ),
        migrations.RemoveField(
            model_name='session',
            name='decisions',
        ),
        migrations.AddField(
            model_name='decision',
            name='session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hangapp.session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='option',
            name='decision',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hangapp.decision'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='option',
            name='usersVoted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hangapp.user'),
        ),
        migrations.AlterField(
            model_name='session',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hangapp.user'),
        ),
    ]
