# Generated by Django 4.0.1 on 2022-01-20 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hangapp', '0002_remove_decision_options_remove_session_decisions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='usersVoted',
        ),
        migrations.RemoveField(
            model_name='session',
            name='users',
        ),
        migrations.AlterField(
            model_name='option',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='hangapp.user'),
        ),
    ]
