# Generated by Django 4.0.1 on 2022-01-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangapp', '0003_option_usersvoted'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='users',
            field=models.ManyToManyField(to='hangapp.User'),
        ),
    ]
