# Generated by Django 4.0.1 on 2022-01-20 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hangapp', '0005_remove_session_id_alter_session_creator_newsession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewSession',
        ),
    ]
