from django.urls import path, include

from . import views

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'options', views.OptionViewSet)
router.register(r'decisions', views.DecisionViewSet)

urlpatterns = [
    path('', views.index, name='index'),

    path('api/', include(router.urls)),  # REST API URLs generated by the Router

    path('start', views.userEntry, name='startUser'),
    path('start/<int:sessionId>', views.userEntryWithSession,
         name='startUserWithSession'),
    path('join', views.newUserNewSession, name='newUserNewSession'),
    path('join/<int:sessionId>', views.newUserJoinSession,
         name='newUserJoinSession'),
    path('addDecision/<int:sessionId>/<int:userId>',
         views.addDecision, name='addDecision'),
    path('suggest/<int:decisionId>/<int:userId>', views.suggest, name='suggest'),
    path('voteSession/<int:sessionId>/<int:userId>',
         views.voteSession, name='voteSession'),
    path('vote/<int:optionId>/<int:userId>', views.vote, name='vote'),
    path('results/<int:decisionId>', views.results, name="results"),
]
