# Generated by Django 4.0.3 on 2022-04-01 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decisionText', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Homie',
            fields=[
                ('username', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionText', models.CharField(max_length=400)),
                ('score', models.FloatField(default=0.0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='hangapp.homie')),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hangapp.decision')),
                ('usersVoted', models.ManyToManyField(to='hangapp.homie')),
            ],
        ),
        migrations.CreateModel(
            name='HangoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='hangapp.homie')),
                ('users', models.ManyToManyField(to='hangapp.homie')),
            ],
        ),
        migrations.AddField(
            model_name='decision',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hangapp.hangoutsession'),
        ),
    ]
