# Generated by Django 4.0.1 on 2022-04-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homie',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hangoutsession',
            name='users',
            field=models.ManyToManyField(to='hangapp.Homie'),
        ),
        migrations.AlterField(
            model_name='option',
            name='usersVoted',
            field=models.ManyToManyField(to='hangapp.Homie'),
        ),
    ]
