# Generated by Django 4.0.1 on 2022-01-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangapp', '0002_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='usersVoted',
            field=models.ManyToManyField(to='hangapp.User'),
        ),
    ]
