# Generated by Django 4.0.3 on 2022-03-24 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hangapp', '0004_session_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Homie',
        ),
    ]
