# Generated by Django 4.0.3 on 2022-03-24 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hangapp', '0005_rename_user_homie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='HangoutSession',
        ),
    ]
